### ISSUE TITLE
mapfilter aura and campfire not working. Currently being controlled by incorrect toggle

### ISSUE THREAD

**Issue by Aipoc76** [macroquest/macroquest#561]
Mapfilter aura off does not toggle auras, they are currently being controlled by Mapfilter object.

Mapfilter campfire does nothing, they are being controlled by Mapfilter NPC

This is reproducible.

**Comment by brainiac** [comment]
> This is reproducible.

please include steps to follow to reproduce.

**Comment by Aipoc76** [comment]
NOTE plugin mq2map needs to be loaded.

1 open map. Ensure show is set to all.
2 look at map if auras are not there, type /mapfilter object.  You should then see auras if the object setting was off to start..
3. type /mapfilter aura.  The map will not change.  Auras will still be shown. and the setting should be off. (if on Type /mapfilter aura again)  Once its off you will notice that the auras are still on the map.

4.  The same process applies to campfires.   Only difference is instead of /mapfilter object, they are being controlled by /mapfilter npc

**Comment by Ortster** [comment]
It looks like this is due to the body type changes that were done. The one Aura I tested with (Aura of the Muse) is showing up as a "Construct" body type now.  Instead of what I am guessing was "Untargetable".

Campfire looks like it keys off being Humanoid type, probably moved to something else as well. Don't have access to that to test.
