### ISSUE TITLE
[MQ2Bzsrch] Bad indexing in search results with a comma in it

### ISSUE THREAD

**Issue by hytiek** [macroquest/macroquest#633]
On Live, searching for "The Diary of Lucca Brightfeld, Part 4" using: 
`/bzsrch The Diary of Lucca Brightfeld, Part 4 type Collectible price 0 9999999`

I am presented with a list:
![image](https://user-images.githubusercontent.com/56261680/192375296-1d68f18d-fce3-4e12-beab-2fb161149e09.png)

Trying to pull info from the results, yields:
> /lua parse mq.TLO.Bazaar.Item(1)()
The Diary of Lucca Brightfeld, Part 7

> /lua parse mq.TLO.Bazaar.Item(1).Name.Equal('The Diary of Lucca Brightfeld, Part 7')()
true

But if I use
`/notify BazaarSearchWnd BZR_Itemlist listselect 1`

It then selects the Part 1 based on the list provided. I would expect the plugin to return the first index value for the Part 7. Is this a problem in approach or a problem with the returned values?

**Comment by brainiac** [comment]
Use SortedItem instead of Item

**Comment by Knightly1** [comment]
A few things to note -- first if you want to do something like that where you have a "weird" item name -- quotes are usually best to delineate where your item name ends.

Second, the bazaar search only supports 30 characters.  You'll note that your item is 38 characters.  So in that case you're almost always better off searching from the right side instead of the left side (for example: "y of Lucca Brightfeld, Part 4") -- otherwise as you see in your screenshot you'll get multiple matches when you want something specific.

Third, your lua parse of the equals is going into the macro language to use the string equals, you're better off using the lua notation rather than dipping into macro language (==)

Finally,  the order of the list and the order of the window are not necessarily the same since the window can be reorganized.  As brainiac mentioned -- if you want them to be the same you need "SortedItem" for comparison.

**Comment by brainiac** [comment]
![all-of-this-pointing](https://user-images.githubusercontent.com/57729/192383741-745df9c6-b0ef-4c39-9c75-7b89c6c4f38c.gif)
