### ISSUE TITLE
%t can sometimes cause the client to crash to desktop. 

### ISSUE THREAD

**Issue by RekkasGit** [macroquest/macroquest#683]
EMU - Laz server. 

Unsure if there is an issue already posted about this but just wanted to note.  

/gu hey i'm fighting %t

the %t can cause a client to crash to desktop. Its happened to me personally at least once, and it seems others as well. at the time I'm 100% sure I had a proper target. 
![image](https://user-images.githubusercontent.com/4657161/212496744-b97545d1-0ccb-4eaf-9937-a9214ad60ed2.png)

**Comment by RekkasGit** [comment]
Want to clarify this is rare, as I cannot really reliably reproduce it.

**Comment by brainiac** [comment]
do you have a crash dump?

**Comment by RekkasGit** [comment]
Where would I find it? I checked  and don't see a dump file for that time period. 
![image](https://user-images.githubusercontent.com/4657161/212497869-b10912a7-0c96-4cf0-813a-6a7fa1316090.png)

**Comment by RekkasGit** [comment]
![image](https://user-images.githubusercontent.com/4657161/212547717-81c18ea8-a59e-42b7-a05a-86127418b083.png)
Yeah I am thinking it just terminates the process, so no dump file is created.

**Comment by Knightly1** [comment]
What is pointing you to MQ for this crash?  In general something like this is going to be an issue in formatting of text (usually a print since % is a token), so the oddity of it being intermittent leads me to believe it might not be MQ.  However, assuming it is MQ it could also be a plugin in that case.  But I would think if it was MQ it would happen every time -- since it's just a buffer parse.  Is there something in common as far as plugins go with the people who are crashing?  What plugins are you running yourself?

Is it only in specific channels?

That code is also the same across Live and Emu as far as parsing text goes and this is the first report I've seen about this.  I would expect it to be more widespread if it was an MQ crash, but maybe it's very specific circumstances?

As a test, I did `/gu %t` with multiple targets a little over 50,000 times.  I also tried multiple ways that I know of that would crash a print and none of them crashed.  I tried the mob in the screenshot -- sleeper (I don't have Larat Grundror on my server) in case there was something specific about that.  With target, without target...

Do you have any more information that might help narrow it down?

**Comment by RekkasGit** [comment]
I have tried myself to reproduce it and I cannot... its totally random and very rare. 
Here is the event viewer entry which isn't horribly useful. 
```
Faulting application name: eqgame.exe, version: 0.0.0.0, time stamp: 0x518de58f
Faulting module name: ntdll.dll, version: 10.0.19041.546, time stamp: 0xd49544eb
Exception code: 0xc0000374
Fault offset: 0x000e6763
Faulting process id: 0x5880
Faulting application start time: 0x01d91c5e1d9ebf3f
Faulting application path: G:\EQ\Project Lazarus\eqgame.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 895cc112-0c56-46d1-bb41-1714694c5b93
Faulting package full name: 
Faulting package-relative application ID: 
```
At this time I will close this until I can get more data of some sort.
