### ISSUE TITLE
Expose new SpellMember for MinLevel

### ISSUE THREAD

**Issue by EQWoobs** [macroquest/macroquest#722]
Expose the Spell's Minimum Class Level. This shows on Alla's as "minlevel". It would save macro writers from having to loop through all the Class Levels to get the minimum. A use case is when I want to check whether my spell is too powerful for my target. I need to check the minimum level, not my class level.

I see we already have a CalcMinSpellLevel function, which looks like what I am looking for.

**Comment by Sicprofundus** [comment]
@EQWoobs this implementation of the MinLevel, if im understanding it correctly, is going to show the "minimum level of any class that can cast/use this spell" and not "give me the lowest level character that can receive this buff".

a spell that shows `RNG/20 DRU/6 SHM/12 ENC/12 BST/25` is going to have a minlevel of `6` because level 6 is the lowest that a character can be to cast the spell (if they were a druid). it is not "a level 6 character is the lowest level that this spell can be cast upon" i don't believe.

being able to know "give me the min level character I could cast this buff upon" would certainly be useful, and I believe that is what you were asking for

**Comment by EQWoobs** [comment]
@Sicprofundus You are correct. There are two different things I was looking at.  MinLevel of 6, in your example, is correct for this enhancement request.  Using that, I can get "the lowest level character that can receive this buff".  It would be nice to also have that also, so I don't have to calculate it, but I didn't want to confuse things. I saw that Alla's showed this as MinLevel, so it seemed reasonable.
Being able to say "give me the min level character I could cast this buff upon" would certainly be useful.  The new MinLevel will save me from doing the first part of the below. The second part, as a direct inquiry on Spell (not having to use it in conjunction with the character - ie WillLand, etc), would definitely be nice.

   /varset tMinClassLevel 255
   /for a 1 to ${Math.Calc[${pcClasses.Count[,]}+1]}
      /if (${Spell[${tSpellID}].Level[${a}]} < ${tMinClassLevel}) {
         /varset tMinClassLevel ${Spell[${tSpellID}].Level[${a}]}
      }
   /next a
   /if (${tMinClassLevel}>=255) /return FALSE
   /if (${tMinClassLevel} > 65) {
      /varset tMinPCLevel 61
   } else /if (${tMinClassLevel} > 50) {
      /varset tMinPCLevel ${Math.Calc[${tMinClassLevel}/2+15].Int}
   }
   /if (${tMinPCLevel}>0 && ${tMinPCLevel}<255) {
	  /return ${tMinPCLevel}
   }
/return FALSE
