### ISSUE TITLE
Spawn TLO Not Filling Out PctMana

### ISSUE THREAD

**Issue by jonnyrocket0** [macroquest/macroquest#772]
**Describe the bug**
The spawn TLO does not fill out PctMana.

**To Reproduce**
1. Query a spawn for PctMana. It will return 0.
2.  ex ${Spawn[anyone].PctMana}

**Expected behavior**
The actual mana percentage is filled out.

**Screenshots**

**MQ Version**
- [ ] Live
- [ ] Test
- [x] Emu (ROF2)  version 3.1.0.142

**Additional context**

**Comment by brainiac** [comment]
Is this in all cases? Does it populate if they are a member if your group?

**Comment by jonnyrocket0** [comment]
Yes, it updates if they are in your group. It then keeps the same value if you remove the person from your group and query it again.

**Comment by dannuic** [comment]
I'm pretty sure that spawns don't send mana information in general (they don't always send health either). In reality, this member should be moved off of spawn and into target, me, and groupmember. That would be breaking however, so I think this is an issue that we cannot fix.

**Comment by jonnyrocket0** [comment]
Is that a limitation of the everquest client? Just wondering why it's different than PctHPs, which works regardless of grouped status.

**Comment by Knightly1** [comment]
It's a limitation on the data that is sent to your client.  Think about it from the perspective of the User Interface:  You can generally see a spawn's hitpoints, but the only time you can see their mana is when it's a player that is grouped with you.

What dannuic mentioned about hitpoints not always being sent is -- have you ever noticed that sometimes you see a mob from far away and you click on it and their hitpoints go from like 30% all the way to full?  (Like a caster gates and then when you get to it their health goes to full?)  Or vice versa, you click on it and it's full and someone is fighting it and you watch the hitpoints immediately drop lower?  That's a function of the data that your client is getting from the server -- sometimes it's out of date and updates when you target/get close.

PctHPs are generally reliable (though not always, I'd only rely on it if I targeted something, in which case  you can just use Target instead of Spawn) but it's reliable because the server is sending that information to your client so that you can display the HitPoints.  There's nothing similar for mana, outside of being grouped with someone.

**Comment by brainiac** [comment]
This behavior is determined by the server. In this case, EQEmu.

**Comment by jonnyrocket0** [comment]
ahhh thank you for the explanation @Knightly1. i will use netbots or a dannet observer for my use case.
