### ISSUE TITLE
[emu] mq::AddAlias seems to be adding entries as a pair/tuple with an uninitialized member

### ISSUE THREAD

**Issue by doubledgedboard** [macroquest/macroquest#895]
**Describe the bug**
When doing plugin development and using `mq::AddAlias`, the alias gets created with invalid characters / format, and what looks like a pair/tuple (instead of a string) where the first is uninitialized

**To Reproduce**
1. Create a plugin
2. Define the InitializePlugin() function
3. Add `AddAlias("/foo", "/foobar");`
4. Compile / Load Plugin
5. Execute /alias list

**Expected behavior**
The alias appears as `/foo : /foobar`

**Actual behavior**
The alias appears with jumbled characters.

**Screenshots**
![image](https://github.com/user-attachments/assets/bfc0cf70-0eaf-4ff6-b045-60de7e891e26)

**MQ Version**
emu

**Additional context**
As a workaround, I can use `DoCommand("/alias /foo /foobar")`

Also, I was unable to debug the method call past this point, as my debugger didn't seem to handle stepping into `mqplugin::MainInterface->AddAlias`. Not sure why?

```
bool mq::AddAlias(const std::string& alias, const std::string& replacement, bool persist)
{
	return mqplugin::MainInterface->AddAlias(alias, replacement, persist, mqplugin::ThisPluginHandle);
}
```

Edit: This also seems to affect `IsAlias()`. Meaning if I manually create `/alias /fb /foobar` in game, and then check `IsAlias("/fb")` in code, it returns `false`;

**Comment by aquietone** [comment]
Unrelated to whether or not there is an actual issue with AddAlias, but do you not want `AddCommand` instead?

**Comment by doubledgedboard** [comment]
@aquietone I'm already using /addcommand for the command itself (which seems to use a stringview instead of a &string)

in this case my intended alias is very short with a chance of collision, so I'm coding it defensively where addcommand adds the long command, and the alias gets added (optionally) if there is no existing conflict

**Comment by Knightly1** [comment]
I'm inclined to believe this is an error in your code for what you're passing to AddAlias, but I also think you're going about it the wrong way.

Command processing means that `/foo` is already short for `/foobar` without adding any aliasing.  What you actually want, if you want to go that route (rather than letting the command interpreter just handle it) would be if you wanted to add disparate commands.  For example: You want `/foo` and `/bar` to do the same thing -- in which case you don't use an alias in a plugin, you are just adding two commands.  But since it's your plugin, why not just use a unique command let the command interpreter handle it?

If you're truly trying to add an alias, I suspect your issue is just in how you're calling it, but without seeing code it's hard to say.

**Comment by doubledgedboard** [comment]
thanks @Knightly1 for the response

Unfortunately the `foo` to `foobar` is just a demonstration value and not a representation of the use case.

The alias needs to be able to be anything, not just a shorter version of the same word.

This is already supported through `/alias`.

So a better example would be `/fb` for `/foobar`, which cannot be shortened just by `/fo`

Here's a code example:

```
PLUGIN_API void InitializePlugin()
{
    AddAlias("/fb", "/foobar");
}

PLUGIN_API void ShutdownPlugin()
{
    RemoveAlias("/fb");
}
```

It's also the same result if providing the bool in the third argument.

For more context, here's an example where someone else was using the method call from inside a plugin in this manner, but it's an old post, so the bug may have cropped up since then:

https://www.mmobugs.com/forums/index.php?threads/popup.7702/

I'm also wanting to rely on `IsAlias` and the other helper methods. IsCommand / AddCommand doesn't have these issues.

**Comment by doubledgedboard** [comment]
Confirmed issue was due to mismatch between versions I was building against and running against.

closing as PEBKAC (I'm dumb)
